spring.profiles.active: dev

spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        # Keep the connection alive if idle for a long time (needed in production)
        testWhileIdle: true
        validationQuery: SELECT 1
    # Show or not log for each sql query
    jpa:
        show-sql: true
    # Hibernate ddl auto (create, create-drop, update)
    hibernate:
        ddl-auto: validate
        # Naming strategy
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    # The SQL dialect makes Hibernate generate better SQL for the chosen database
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect


---
# 开发环境
spring:
    profiles: dev
    datasource:
        url: jdbc:mysql://localhost:3306/hostel
        username: root
        password: root



server:
    port: 8091

#logging.config: classpath:log4j2.yaml
#logging.access.enabled: false
spring.jpa.show-sql: false
